// Mapeamento de regiões geográficas
const regionMapping = {
    'África': ['África do Sul', 'Egito', 'Marrocos', 'Tunísia', 'Argélia', 'Nigéria', 'Gana', 'Senegal', 'Cabo Verde'],
    'América Central': ['Costa Rica', 'Panamá', 'Honduras', 'El Salvador', 'Guatemala', 'Belize', 'Nicarágua'],
    'América do Norte': ['Estados Unidos', 'Estados Unidos (Alaska)', 'Canadá', 'México'],
    'América do Sul': ['Brasil', 'Argentina', 'Chile', 'Peru', 'Colômbia', 'Venezuela', 'Guiana', 'Suriname', 'Equador', 'Bolívia', 'Paraguai', 'Uruguai'],
    'Ásia': ['Japão', 'Coreia do Sul', 'China', 'Hong Kong', 'Taiwan', 'Singapura', 'Tailândia', 'Malásia', 'Indonésia', 'Filipinas', 'Índia', 'Bangladesh', 'Rússia'],
    'Atlântico Norte': ['Islândia', 'Groelândia', 'Ilhas Faroe'],
    'Caribe': ['República Dominicana', 'Porto Rico', 'Cuba', 'Jamaica', 'Barbados', 'Trinidad e Tobago', 'Curaçao', 'Aruba', 'Bonaire', 'Sint Maarten', 'São Martinho', 'Ilhas Virgens Americanas', 'Bahamas', 'Ilhas Cayman', 'Antígua e Barbuda', 'Santa Lúcia', 'Granada', 'São Vicente e Granadinas', 'Guadalupe', 'Martinica', 'Guiana Francesa', 'Saba', 'Sint Eustatius', 'São Bartolomeu', 'Dominica', 'São Cristóvão e Névis'],
    'Europa': ['Reino Unido', 'França', 'Alemanha', 'Holanda', 'Bélgica', 'Espanha', 'Portugal', 'Portugal (Açores)', 'Itália', 'Suíça', 'Áustria', 'Dinamarca', 'Noruega', 'Suécia', 'Finlândia'],
    'Ilhas do Atlântico': ['Santa Helena', 'Reunião', 'Maurício'],
    'Ilhas do Índico': ['Seychelles', 'Maldivas'],
    'Oceania': ['Austrália', 'Nova Zelândia', 'Fiji', 'Samoa', 'Samoa Americana', 'Nova Caledônia', 'Papua Nova Guiné'],
    'Oriente Médio': ['Emirados Árabes Unidos', 'Qatar', 'Kuwait', 'Bahrain', 'Omã', 'Arábia Saudita'],
    'Pacífico': ['Estados Unidos (Havaí)', 'Guam', 'Ilhas Marianas do Norte']
};

// Base de dados de fabricantes e modelos de aeronaves A JATO
const aircraftDatabase = {
    'aerion': {
        name: 'Aerion Supersonic',
        models: {
            'as2': { name: 'AS2 (Supersonic)', range: 9260 } // Projeto em desenvolvimento
        }
    },
    'airbus': {
        name: 'Airbus Corporate Jets',
        models: {
            'acj220': { name: 'ACJ TwoTwenty', range: 12964 },
            'acj319': { name: 'ACJ319neo', range: 13334 },
            'acj320': { name: 'ACJ320neo', range: 11112 },
            'acj321': { name: 'ACJ321neo', range: 13889 },
            'acj330': { name: 'ACJ330', range: 18519 },
            'acj350': { name: 'ACJ350', range: 20186 }
        }
    },
    'boeing': {
        name: 'Boeing Business Jets',
        models: {
            'bbj': { name: 'BBJ (737-700)', range: 10186 },
            'bbj2': { name: 'BBJ2 (737-800)', range: 10186 },
            'bbj3': { name: 'BBJ3 (737-900ER)', range: 9260 },
            'bbj-max-7': { name: 'BBJ MAX 7', range: 12964 },
            'bbj-max-8': { name: 'BBJ MAX 8', range: 11112 },
            'bbj-max-9': { name: 'BBJ MAX 9', range: 10186 },
            'bbj-787-8': { name: 'BBJ 787-8 Dreamliner', range: 18519 },
            'bbj-787-9': { name: 'BBJ 787-9 Dreamliner', range: 20372 },
            'bbj-777': { name: 'BBJ 777', range: 18519 },
            'bbj-747': { name: 'BBJ 747-8', range: 19446 }
        }
    },
    'bombardier': {
        name: 'Bombardier',
        models: {
            'learjet-75': { name: 'Learjet 75', range: 3889 },
            'challenger-350': { name: 'Challenger 350', range: 5926 },
            'challenger-650': { name: 'Challenger 650', range: 7408 },
            'global-5500': { name: 'Global 5500', range: 11112 },
            'global-6500': { name: 'Global 6500', range: 12408 },
            'global-7500': { name: 'Global 7500', range: 14260 },
            'global-8000': { name: 'Global 8000', range: 15186 } // Lançamento 2025
        }
    },
    'boom': {
        name: 'Boom Supersonic',
        models: {
            'overture': { name: 'Overture (Supersonic)', range: 8334 } // Lançamento 2029
        }
    },
    'cirrus': {
        name: 'Cirrus',
        models: {
            'sf50-vision': { name: 'SF50 Vision Jet', range: 1852 }
        }
    },
    'cessna': {
        name: 'Cessna Citation',
        models: {
            'citation-m2': { name: 'Citation M2', range: 2593 },
            'citation-cj3': { name: 'Citation CJ3+', range: 3778 },
            'citation-cj4': { name: 'Citation CJ4', range: 3889 },
            'citation-latitude': { name: 'Citation Latitude', range: 5000 },
            'citation-longitude': { name: 'Citation Longitude', range: 6482 },
            'citation-sovereign': { name: 'Citation Sovereign+', range: 5556 },
            'citation-xls': { name: 'Citation XLS+', range: 4074 }
        }
    },
    'dassault': {
        name: 'Dassault Falcon',
        models: {
            'falcon-2000': { name: 'Falcon 2000', range: 5556 },
            'falcon-6x': { name: 'Falcon 6X', range: 10186 },
            'falcon-7x': { name: 'Falcon 7X', range: 11019 },
            'falcon-8x': { name: 'Falcon 8X', range: 11945 },
            'falcon-900': { name: 'Falcon 900', range: 8334 },
            'falcon-10x': { name: 'Falcon 10X', range: 13890 } // Lançamento 2027
        }
    },
    'embraer': {
        name: 'Embraer',
        models: {
            'phenom-100': { name: 'Phenom 100', range: 2182 },
            'phenom-300': { name: 'Phenom 300', range: 3334 },
            'praetor-500': { name: 'Praetor 500', range: 5556 },
            'praetor-600': { name: 'Praetor 600', range: 7408 },
            'praetor-700': { name: 'Praetor 700', range: 8334 }, // Lançamento 2027
            'legacy-450': { name: 'Legacy 450', range: 4260 },
            'legacy-500': { name: 'Legacy 500', range: 5556 },
            'legacy-650': { name: 'Legacy 650', range: 7223 }
        }
    },
    'gulfstream': {
        name: 'Gulfstream',
        models: {
            'g280': { name: 'G280', range: 6667 },
            'g400': { name: 'G400', range: 8334 }, // Lançamento 2025
            'g500': { name: 'G500', range: 9260 },
            'g600': { name: 'G600', range: 11112 },
            'g650': { name: 'G650', range: 12964 },
            'g650er': { name: 'G650ER', range: 13890 },
            'g700': { name: 'G700', range: 13890 },
            'g800': { name: 'G800', range: 14816 }
        }
    }
    'honda': {
        name: 'Honda Aircraft',
        models: {
            'hondajet-ha420': { name: 'HondaJet HA-420', range: 2265 },
            'hondajet-2600': { name: 'HondaJet 2600', range: 4815 }, // Lançamento 2028
            'hondajet-echelon': { name: 'HondaJet Echelon', range: 6482 } // Lançamento 2029
        }
    }
};

// Base de dados expandida de aeroportos mundiais para aviação executiva
const airportsDatabase = [
    // BRASIL - Expandido drasticamente
    { code: 'GRU', city: 'São Paulo', country: 'Brasil', lat: -23.4356, lng: -46.4731, name: 'Guarulhos International Airport' },
    { code: 'GIG', city: 'Rio de Janeiro', country: 'Brasil', lat: -22.8099, lng: -43.2505, name: 'Galeão International Airport' },
    { code: 'BSB', city: 'Brasília', country: 'Brasil', lat: -15.8711, lng: -47.9172, name: 'Brasília International Airport' },
    { code: 'CGH', city: 'São Paulo', country: 'Brasil', lat: -23.6262, lng: -46.6561, name: 'Congonhas Airport' },
    { code: 'SDU', city: 'Rio de Janeiro', country: 'Brasil', lat: -22.9099, lng: -43.1634, name: 'Santos Dumont Airport' },
    { code: 'REC', city: 'Recife', country: 'Brasil', lat: -8.1265, lng: -34.9236, name: 'Recife International Airport' },
    { code: 'FOR', city: 'Fortaleza', country: 'Brasil', lat: -3.7763, lng: -38.5326, name: 'Fortaleza International Airport' },
    { code: 'MAO', city: 'Manaus', country: 'Brasil', lat: -3.0386, lng: -60.0497, name: 'Eduardo Gomes International Airport' },
    { code: 'SSA', city: 'Salvador', country: 'Brasil', lat: -12.9086, lng: -38.3224, name: 'Salvador International Airport' },
    { code: 'BEL', city: 'Belém', country: 'Brasil', lat: -1.3793, lng: -48.4736, name: 'Val de Cans International Airport' },
    { code: 'CWB', city: 'Curitiba', country: 'Brasil', lat: -25.5285, lng: -49.1758, name: 'Afonso Pena International Airport' },
    { code: 'POA', city: 'Porto Alegre', country: 'Brasil', lat: -29.9939, lng: -51.1711, name: 'Salgado Filho International Airport' },
    { code: 'FLN', city: 'Florianópolis', country: 'Brasil', lat: -27.6704, lng: -48.5525, name: 'Hercílio Luz International Airport' },
    { code: 'VIX', city: 'Vitória', country: 'Brasil', lat: -20.2581, lng: -40.2864, name: 'Eurico de Aguiar Salles Airport' },
    { code: 'CNF', city: 'Belo Horizonte', country: 'Brasil', lat: -19.6244, lng: -43.9719, name: 'Tancredo Neves International Airport' },
    { code: 'SLZ', city: 'São Luís', country: 'Brasil', lat: -2.5859, lng: -44.2341, name: 'Marechal Cunha Machado International Airport' },
    { code: 'THE', city: 'Teresina', country: 'Brasil', lat: -5.0596, lng: -42.8234, name: 'Teresina Airport' },
    { code: 'NAT', city: 'Natal', country: 'Brasil', lat: -5.9111, lng: -35.2476, name: 'Augusto Severo International Airport' },
    { code: 'JPA', city: 'João Pessoa', country: 'Brasil', lat: -7.1469, lng: -34.9486, name: 'Presidente Castro Pinto International Airport' },
    { code: 'MCZ', city: 'Maceió', country: 'Brasil', lat: -9.5108, lng: -35.7917, name: 'Zumbi dos Palmares International Airport' },
    { code: 'AJU', city: 'Aracaju', country: 'Brasil', lat: -10.9840, lng: -37.0703, name: 'Santa Maria Airport' },
    { code: 'IOS', city: 'Ilhéus', country: 'Brasil', lat: -14.8159, lng: -39.0333, name: 'Jorge Amado Airport' },
    { code: 'VDC', city: 'Vitória da Conquista', country: 'Brasil', lat: -14.8626, lng: -40.8631, name: 'Glauber Rocha Airport' },
    { code: 'BPS', city: 'Porto Seguro', country: 'Brasil', lat: -16.4386, lng: -39.0808, name: 'Porto Seguro Airport' },
    { code: 'GYN', city: 'Goiânia', country: 'Brasil', lat: -16.6320, lng: -49.2207, name: 'Santa Genoveva Airport' },
    { code: 'CGB', city: 'Cuiabá', country: 'Brasil', lat: -15.6529, lng: -56.1167, name: 'Marechal Rondon International Airport' },
    { code: 'CGR', city: 'Campo Grande', country: 'Brasil', lat: -20.4687, lng: -54.6725, name: 'Campo Grande Airport' },
    { code: 'CXJ', city: 'Caxias do Sul', country: 'Brasil', lat: -29.1967, lng: -51.1875, name: 'Hugo Cantergiani Regional Airport' },
    { code: 'JOI', city: 'Joinville', country: 'Brasil', lat: -26.2244, lng: -48.7977, name: 'Lauro Carneiro de Loyola Airport' },
    { code: 'NVT', city: 'Navegantes', country: 'Brasil', lat: -26.8800, lng: -48.6511, name: 'Ministro Victor Konder International Airport' },
    { code: 'PFB', city: 'Passo Fundo', country: 'Brasil', lat: -28.2439, lng: -52.3265, name: 'Lauro Kurtz Airport' },
    { code: 'UDI', city: 'Uberlândia', country: 'Brasil', lat: -18.8825, lng: -48.2253, name: 'Uberlândia Airport' },
    { code: 'MOC', city: 'Montes Claros', country: 'Brasil', lat: -16.7069, lng: -43.8189, name: 'Montes Claros Airport' },
    { code: 'JDF', city: 'Juiz de Fora', country: 'Brasil', lat: -21.7915, lng: -43.3869, name: 'Francisco Alvares de Assis Chateaubriand Airport' },
    { code: 'CAW', city: 'Campos dos Goytacazes', country: 'Brasil', lat: -21.6983, lng: -41.3017, name: 'Bartolomeu Lysandro Airport' },
    { code: 'MVF', city: 'Mossoró', country: 'Brasil', lat: -5.2017, lng: -37.3644, name: 'Dix-Sept Rosado Airport' },
    { code: 'CPV', city: 'Campina Grande', country: 'Brasil', lat: -7.2697, lng: -35.8956, name: 'Presidente João Suassuna Airport' },
    { code: 'PNZ', city: 'Petrolina', country: 'Brasil', lat: -9.3624, lng: -40.5691, name: 'Senador Nilo Coelho Airport' },
    { code: 'JUA', city: 'Juazeiro do Norte', country: 'Brasil', lat: -7.2189, lng: -39.2697, name: 'Orlando Bezerra de Menezes Airport' },
    { code: 'VCP', city: 'Campinas', country: 'Brasil', lat: -23.0074, lng: -47.1344, name: 'Viracopos International Airport' },
    { code: 'SJK', city: 'São José dos Campos', country: 'Brasil', lat: -23.2281, lng: -45.8619, name: 'Professor Urbano Ernesto Stumpf Airport' },
    { code: 'JTC', city: 'Rio de Janeiro', country: 'Brasil', lat: -22.9758, lng: -43.3689, name: 'Jacarepaguá Airport' },
    { code: 'PLU', city: 'Belo Horizonte', country: 'Brasil', lat: -19.8508, lng: -43.9506, name: 'Carlos Drummond de Andrade Airport (Pampulha)' },
    { code: 'IPN', city: 'Ipatinga', country: 'Brasil', lat: -19.4703, lng: -42.4875, name: 'Usiminas Airport' },
    { code: 'RAO', city: 'Ribeirão Preto', country: 'Brasil', lat: -21.1342, lng: -47.7769, name: 'Leite Lopes Airport' },
    { code: 'SJP', city: 'São José do Rio Preto', country: 'Brasil', lat: -20.8156, lng: -49.4069, name: 'Professor Eribelto Manoel Reino State Airport' },
    { code: 'ARU', city: 'Araçatuba', country: 'Brasil', lat: -21.1411, lng: -50.4253, name: 'Dracena Airport' },
    { code: 'PPB', city: 'Presidente Prudente', country: 'Brasil', lat: -22.1750, lng: -51.4242, name: 'Presidente Prudente Airport' },
    { code: 'LDB', city: 'Londrina', country: 'Brasil', lat: -23.3336, lng: -51.1300, name: 'Governador José Richa Airport' },
    { code: 'CAC', city: 'Cascavel', country: 'Brasil', lat: -25.0033, lng: -53.5008, name: 'Adalberto Mendes da Silva Airport' },
    { code: 'IGU', city: 'Foz do Iguaçu', country: 'Brasil', lat: -25.6000, lng: -54.4847, name: 'Cataratas International Airport' },
    { code: 'URG', city: 'Uruguaiana', country: 'Brasil', lat: -29.7822, lng: -57.0381, name: 'Rubem Berta International Airport' },
    { code: 'PET', city: 'Pelotas', country: 'Brasil', lat: -31.7186, lng: -52.3275, name: 'João Simões Lopes Neto International Airport' },
    { code: 'RIA', city: 'Santa Maria', country: 'Brasil', lat: -29.7114, lng: -53.6881, name: 'Santa Maria Airport' },
    { code: 'BVB', city: 'Boa Vista', country: 'Brasil', lat: 2.8461, lng: -60.6903, name: 'Atlas Brasil Cantanhede International Airport' },
    { code: 'RBR', city: 'Rio Branco', country: 'Brasil', lat: -9.8658, lng: -67.8986, name: 'Plácido de Castro International Airport' },
    { code: 'PVH', city: 'Porto Velho', country: 'Brasil', lat: -8.7097, lng: -63.9028, name: 'Governador Jorge Teixeira de Oliveira International Airport' },
    { code: 'MAB', city: 'Marabá', country: 'Brasil', lat: -5.3686, lng: -49.1381, name: 'João Correa da Rocha Airport' },
    { code: 'STM', city: 'Santarém', country: 'Brasil', lat: -2.4247, lng: -54.7856, name: 'Maestro Wilson Fonseca Airport' },
    { code: 'CZS', city: 'Cruzeiro do Sul', country: 'Brasil', lat: -7.5997, lng: -72.7694, name: 'Cruzeiro do Sul International Airport' },
    { code: 'FEN', city: 'Fernando de Noronha', country: 'Brasil', lat: -3.8489, lng: -32.4233, name: 'Fernando de Noronha Airport' },
    { code: 'IMP', city: 'Imperatriz', country: 'Brasil', lat: -5.5314, lng: -47.4603, name: 'Prefeito Renato Moreira Airport' },
    { code: 'BRA', city: 'Barreiras', country: 'Brasil', lat: -12.0789, lng: -44.9942, name: 'Barreiras Airport' },
    { code: 'ROO', city: 'Rondonópolis', country: 'Brasil', lat: -16.5867, lng: -54.7250, name: 'Maestro Marinho Franco Airport' },
    { code: 'COR', city: 'Corumbá', country: 'Brasil', lat: -19.0119, lng: -57.6733, name: 'Corumbá International Airport' },
    { code: 'BYO', city: 'Bonito', country: 'Brasil', lat: -21.2469, lng: -56.4519, name: 'Bonito Airport' },
    { code: 'AQA', city: 'Aquidauana', country: 'Brasil', lat: -20.4669, lng: -55.7669, name: 'Aquidauana Airport' },

    // ESTADOS UNIDOS - Expandido drasticamente
    { code: 'JFK', city: 'New York', country: 'Estados Unidos', lat: 40.6413, lng: -73.7781, name: 'John F. Kennedy International Airport' },
    { code: 'LGA', city: 'New York', country: 'Estados Unidos', lat: 40.7769, lng: -73.8740, name: 'LaGuardia Airport' },
    { code: 'EWR', city: 'New York', country: 'Estados Unidos', lat: 40.6895, lng: -74.1745, name: 'Newark Liberty International Airport' },
    { code: 'TEB', city: 'Teterboro', country: 'Estados Unidos', lat: 40.8501, lng: -74.0606, name: 'Teterboro Airport' },
    { code: 'HPN', city: 'White Plains', country: 'Estados Unidos', lat: 41.0670, lng: -73.7076, name: 'Westchester County Airport' },
    { code: 'LAX', city: 'Los Angeles', country: 'Estados Unidos', lat: 33.9425, lng: -118.4081, name: 'Los Angeles International Airport' },
    { code: 'BUR', city: 'Burbank', country: 'Estados Unidos', lat: 34.2007, lng: -118.3585, name: 'Hollywood Burbank Airport' },
    { code: 'LGB', city: 'Long Beach', country: 'Estados Unidos', lat: 33.8177, lng: -118.1516, name: 'Long Beach Airport' },
    { code: 'SNA', city: 'Orange County', country: 'Estados Unidos', lat: 33.6757, lng: -117.8683, name: 'John Wayne Airport' },
    { code: 'VNY', city: 'Van Nuys', country: 'Estados Unidos', lat: 34.2098, lng: -118.4898, name: 'Van Nuys Airport' },
    { code: 'MIA', city: 'Miami', country: 'Estados Unidos', lat: 25.7959, lng: -80.2871, name: 'Miami International Airport' },
    { code: 'FLL', city: 'Fort Lauderdale', country: 'Estados Unidos', lat: 26.0742, lng: -80.1506, name: 'Fort Lauderdale-Hollywood International Airport' },
    { code: 'PBI', city: 'West Palm Beach', country: 'Estados Unidos', lat: 26.6832, lng: -80.0956, name: 'Palm Beach International Airport' },
    { code: 'OPF', city: 'Miami', country: 'Estados Unidos', lat: 25.9070, lng: -80.2784, name: 'Opa-locka Executive Airport' },
    { code: 'TMB', city: 'Miami', country: 'Estados Unidos', lat: 25.6479, lng: -80.4328, name: 'Kendall-Tamiami Executive Airport' },
    { code: 'ORD', city: 'Chicago', country: 'Estados Unidos', lat: 41.9742, lng: -87.9073, name: 'O\'Hare International Airport' },
    { code: 'MDW', city: 'Chicago', country: 'Estados Unidos', lat: 41.7868, lng: -87.7524, name: 'Midway International Airport' },
    { code: 'PWK', city: 'Chicago', country: 'Estados Unidos', lat: 42.1142, lng: -87.9015, name: 'Chicago Executive Airport' },
    { code: 'DFW', city: 'Dallas', country: 'Estados Unidos', lat: 32.8998, lng: -97.0403, name: 'Dallas/Fort Worth International Airport' },
    { code: 'DAL', city: 'Dallas', country: 'Estados Unidos', lat: 32.8471, lng: -96.8518, name: 'Dallas Love Field' },
    { code: 'ADS', city: 'Dallas', country: 'Estados Unidos', lat: 32.9686, lng: -96.8364, name: 'Addison Airport' },
    { code: 'ATL', city: 'Atlanta', country: 'Estados Unidos', lat: 33.6407, lng: -84.4277, name: 'Hartsfield-Jackson Atlanta International Airport' },
    { code: 'PDK', city: 'Atlanta', country: 'Estados Unidos', lat: 33.8756, lng: -84.3020, name: 'DeKalb-Peachtree Airport' },
    { code: 'LAS', city: 'Las Vegas', country: 'Estados Unidos', lat: 36.0840, lng: -115.1537, name: 'McCarran International Airport' },
    { code: 'HDN', city: 'Las Vegas', country: 'Estados Unidos', lat: 36.2377, lng: -115.1344, name: 'Henderson Executive Airport' },
    { code: 'SFO', city: 'San Francisco', country: 'Estados Unidos', lat: 37.6213, lng: -122.3790, name: 'San Francisco International Airport' },
    { code: 'SJC', city: 'San Jose', country: 'Estados Unidos', lat: 37.3626, lng: -121.9291, name: 'Norman Y. Mineta San José International Airport' },
    { code: 'PAO', city: 'Palo Alto', country: 'Estados Unidos', lat: 37.4611, lng: -122.1150, name: 'Palo Alto Airport' },
    { code: 'SEA', city: 'Seattle', country: 'Estados Unidos', lat: 47.4502, lng: -122.3088, name: 'Seattle-Tacoma International Airport' },
    { code: 'BFI', city: 'Seattle', country: 'Estados Unidos', lat: 47.5300, lng: -122.3019, name: 'Boeing Field' },
    { code: 'BOS', city: 'Boston', country: 'Estados Unidos', lat: 42.3656, lng: -71.0096, name: 'Logan International Airport' },
    { code: 'BED', city: 'Boston', country: 'Estados Unidos', lat: 42.4700, lng: -71.2889, name: 'Laurence G. Hanscom Field' },
    { code: 'DCA', city: 'Washington', country: 'Estados Unidos', lat: 38.8521, lng: -77.0377, name: 'Ronald Reagan Washington National Airport' },
    { code: 'IAD', city: 'Washington', country: 'Estados Unidos', lat: 38.9445, lng: -77.4558, name: 'Washington Dulles International Airport' },
    { code: 'BWI', city: 'Baltimore', country: 'Estados Unidos', lat: 39.1754, lng: -76.6682, name: 'Baltimore/Washington International Airport' },
    { code: 'PHL', city: 'Philadelphia', country: 'Estados Unidos', lat: 39.8729, lng: -75.2437, name: 'Philadelphia International Airport' },
    { code: 'PNE', city: 'Philadelphia', country: 'Estados Unidos', lat: 40.0822, lng: -75.0106, name: 'Northeast Philadelphia Airport' },
    { code: 'DEN', city: 'Denver', country: 'Estados Unidos', lat: 39.8561, lng: -104.6737, name: 'Denver International Airport' },
    { code: 'APA', city: 'Denver', country: 'Estados Unidos', lat: 39.5701, lng: -104.8493, name: 'Centennial Airport' },
    { code: 'PHX', city: 'Phoenix', country: 'Estados Unidos', lat: 33.4484, lng: -112.0740, name: 'Phoenix Sky Harbor International Airport' },
    { code: 'SDL', city: 'Scottsdale', country: 'Estados Unidos', lat: 33.6228, lng: -111.9105, name: 'Scottsdale Airport' },
    { code: 'MSP', city: 'Minneapolis', country: 'Estados Unidos', lat: 44.8848, lng: -93.2223, name: 'Minneapolis-Saint Paul International Airport' },
    { code: 'FCM', city: 'Minneapolis', country: 'Estados Unidos', lat: 45.1275, lng: -93.2117, name: 'Flying Cloud Airport' },

    // ALASKA
    { code: 'ANC', city: 'Anchorage', country: 'Estados Unidos (Alaska)', lat: 61.2181, lng: -149.9003, name: 'Ted Stevens Anchorage International Airport' },
    { code: 'FAI', city: 'Fairbanks', country: 'Estados Unidos (Alaska)', lat: 64.8378, lng: -147.8564, name: 'Fairbanks International Airport' },
    { code: 'JNU', city: 'Juneau', country: 'Estados Unidos (Alaska)', lat: 58.3550, lng: -134.5764, name: 'Juneau International Airport' },
    { code: 'KTN', city: 'Ketchikan', country: 'Estados Unidos (Alaska)', lat: 55.3556, lng: -131.7136, name: 'Ketchikan International Airport' },

    // CANADÁ - Expandido
    { code: 'YYZ', city: 'Toronto', country: 'Canadá', lat: 43.6777, lng: -79.6248, name: 'Toronto Pearson International Airport' },
    { code: 'YTZ', city: 'Toronto', country: 'Canadá', lat: 43.6275, lng: -79.3962, name: 'Billy Bishop Toronto City Airport' },
    { code: 'YKZ', city: 'Toronto', country: 'Canadá', lat: 43.8619, lng: -79.3747, name: 'Buttonville Municipal Airport' },
    { code: 'YVR', city: 'Vancouver', country: 'Canadá', lat: 49.1967, lng: -123.1815, name: 'Vancouver International Airport' },
    { code: 'YUL', city: 'Montreal', country: 'Canadá', lat: 45.4647, lng: -73.7453, name: 'Montréal-Pierre Elliott Trudeau International Airport' },
    { code: 'YHU', city: 'Montreal', country: 'Canadá', lat: 45.5175, lng: -73.4169, name: 'Montréal-Saint-Hubert Longueuil Airport' },
    { code: 'YOW', city: 'Ottawa', country: 'Canadá', lat: 45.3192, lng: -75.6692, name: 'Ottawa Macdonald-Cartier International Airport' },
    { code: 'YYC', city: 'Calgary', country: 'Canadá', lat: 51.1225, lng: -114.0200, name: 'Calgary International Airport' },
    { code: 'YEG', city: 'Edmonton', country: 'Canadá', lat: 53.3097, lng: -113.5803, name: 'Edmonton International Airport' },
    { code: 'YWG', city: 'Winnipeg', country: 'Canadá', lat: 49.9100, lng: -97.2394, name: 'Winnipeg James Armstrong Richardson International Airport' },
    { code: 'YHZ', city: 'Halifax', country: 'Canadá', lat: 44.8808, lng: -63.5086, name: 'Halifax Stanfield International Airport' },
    { code: 'YQB', city: 'Quebec City', country: 'Canadá', lat: 46.7911, lng: -71.3933, name: 'Québec City Jean Lesage International Airport' },

    // CARIBE - Expandido
    { code: 'PUJ', city: 'Punta Cana', country: 'República Dominicana', lat: 18.5674, lng: -68.3634, name: 'Punta Cana International Airport' },
    { code: 'SDQ', city: 'Santo Domingo', country: 'República Dominicana', lat: 18.4297, lng: -69.6689, name: 'Las Américas International Airport' },
    { code: 'STI', city: 'Santiago', country: 'República Dominicana', lat: 19.4061, lng: -70.6047, name: 'Cibao International Airport' },
    { code: 'SJU', city: 'San Juan', country: 'Porto Rico', lat: 18.4394, lng: -66.0017, name: 'Luis Muñoz Marín International Airport' },
    { code: 'BQN', city: 'Aguadilla', country: 'Porto Rico', lat: 18.4947, lng: -67.1294, name: 'Rafael Hernández Airport' },
    { code: 'PSE', city: 'Ponce', country: 'Porto Rico', lat: 18.0083, lng: -66.5631, name: 'Mercedita Airport' },
    { code: 'HAV', city: 'Havana', country: 'Cuba', lat: 22.9892, lng: -82.4091, name: 'José Martí International Airport' },
    { code: 'VRA', city: 'Varadero', country: 'Cuba', lat: 23.0342, lng: -81.4353, name: 'Juan Gualberto Gómez Airport' },
    { code: 'KIN', city: 'Kingston', country: 'Jamaica', lat: 17.9357, lng: -76.7875, name: 'Norman Manley International Airport' },
    { code: 'MBJ', city: 'Montego Bay', country: 'Jamaica', lat: 18.5037, lng: -77.9134, name: 'Sangster International Airport' },
    { code: 'BGI', city: 'Bridgetown', country: 'Barbados', lat: 13.0761, lng: -59.4925, name: 'Grantley Adams International Airport' },
    { code: 'POS', city: 'Port of Spain', country: 'Trinidad e Tobago', lat: 10.5955, lng: -61.3372, name: 'Piarco International Airport' },
    { code: 'CUR', city: 'Willemstad', country: 'Curaçao', lat: 12.1889, lng: -68.9597, name: 'Curaçao International Airport' },
    { code: 'AUA', city: 'Oranjestad', country: 'Aruba', lat: 12.5014, lng: -70.0152, name: 'Queen Beatrix International Airport' },
    { code: 'SXM', city: 'Philipsburg', country: 'Sint Maarten', lat: 18.0406, lng: -63.1089, name: 'Princess Juliana International Airport' },
    { code: 'STT', city: 'Charlotte Amalie', country: 'Ilhas Virgens Americanas', lat: 18.3373, lng: -64.9733, name: 'Cyril E. King Airport' },
    { code: 'STX', city: 'Christiansted', country: 'Ilhas Virgens Americanas', lat: 17.7019, lng: -64.7986, name: 'Henry E. Rohlsen Airport' },
    { code: 'NAS', city: 'Nassau', country: 'Bahamas', lat: 25.0389, lng: -77.4661, name: 'Lynden Pindling International Airport' },
    { code: 'FPO', city: 'Freeport', country: 'Bahamas', lat: 26.5581, lng: -78.6956, name: 'Grand Bahama International Airport' },
    { code: 'GCM', city: 'George Town', country: 'Ilhas Cayman', lat: 19.2928, lng: -81.3578, name: 'Owen Roberts International Airport' },
    { code: 'ANU', city: 'St. John\'s', country: 'Antígua e Barbuda', lat: 17.1367, lng: -61.7928, name: 'V.C. Bird International Airport' },
    { code: 'UVF', city: 'Vieux Fort', country: 'Santa Lúcia', lat: 13.7331, lng: -60.9528, name: 'Hewanorra International Airport' },
    { code: 'GND', city: 'St. George\'s', country: 'Granada', lat: 12.0042, lng: -61.7861, name: 'Maurice Bishop International Airport' },
    { code: 'SVD', city: 'Kingstown', country: 'São Vicente e Granadinas', lat: 13.1439, lng: -61.2108, name: 'Argyle International Airport' },

    // CARIBE 
    { code: 'PTP', city: 'Pointe-à-Pitre', country: 'Guadalupe', lat: 16.2653, lng: -61.5317, name: 'Pointe-à-Pitre International Airport' },
    { code: 'FDF', city: 'Fort-de-France', country: 'Martinica', lat: 14.5909, lng: -61.0031, name: 'Martinique Aimé Césaire International Airport' },
    { code: 'CAY', city: 'Cayenne', country: 'Guiana Francesa', lat: 4.8197, lng: -52.3603, name: 'Cayenne – Félix Eboué Airport' },
    { code: 'BON', city: 'Kralendijk', country: 'Bonaire', lat: 12.1311, lng: -68.2685, name: 'Flamingo International Airport' },
    { code: 'SAB', city: 'The Bottom', country: 'Saba', lat: 17.6455, lng: -63.2202, name: 'Juancho E. Yrausquin Airport' },
    { code: 'EUX', city: 'Oranjestad', country: 'Sint Eustatius', lat: 17.4964, lng: -62.9794, name: 'F. D. Roosevelt Airport' },
    { code: 'SBH', city: 'Gustavia', country: 'São Bartolomeu', lat: 17.9044, lng: -62.8436, name: 'Gustaf III Airport' },
    { code: 'SFG', city: 'Marigot', country: 'São Martinho', lat: 18.1006, lng: -63.0472, name: 'L\'Espérance Airport' },
    { code: 'DOM', city: 'Roseau', country: 'Dominica', lat: 15.5469, lng: -61.3000, name: 'Douglas-Charles Airport' },
    { code: 'SKB', city: 'Basseterre', country: 'São Cristóvão e Névis', lat: 17.3111, lng: -62.7178, name: 'Robert L. Bradshaw International Airport' },


    // AMÉRICA DO SUL - Expandido
    { code: 'EZE', city: 'Buenos Aires', country: 'Argentina', lat: -34.8222, lng: -58.5358, name: 'Ezeiza International Airport' },
    { code: 'AEP', city: 'Buenos Aires', country: 'Argentina', lat: -34.5592, lng: -58.4156, name: 'Jorge Newbery Airfield' },
    { code: 'COR', city: 'Córdoba', country: 'Argentina', lat: -31.3236, lng: -64.2081, name: 'Córdoba Airport' },
    { code: 'MDZ', city: 'Mendoza', country: 'Argentina', lat: -32.8317, lng: -68.7928, name: 'Governor Francisco Gabrielli International Airport' },
    { code: 'IGR', city: 'Iguazu', country: 'Argentina', lat: -25.7372, lng: -54.4736, name: 'Cataratas del Iguazú International Airport' },
    { code: 'BRC', city: 'Bariloche', country: 'Argentina', lat: -41.1511, lng: -71.1575, name: 'San Carlos de Bariloche Airport' },
    { code: 'USH', city: 'Ushuaia', country: 'Argentina', lat: -54.8433, lng: -68.2958, name: 'Malvinas Argentinas Ushuaia International Airport' },
    { code: 'SCL', city: 'Santiago', country: 'Chile', lat: -33.3928, lng: -70.7858, name: 'Arturo Merino Benítez International Airport' },
    { code: 'IPC', city: 'Easter Island', country: 'Chile', lat: -27.1648, lng: -109.4219, name: 'Mataveri International Airport' },
    { code: 'ARI', city: 'Arica', country: 'Chile', lat: -18.3486, lng: -70.3389, name: 'Chacalluta International Airport' },
    { code: 'CJC', city: 'Calama', country: 'Chile', lat: -22.4981, lng: -68.9036, name: 'El Loa Airport' },
    { code: 'LIM', city: 'Lima', country: 'Peru', lat: -12.0219, lng: -77.1143, name: 'Jorge Chávez International Airport' },
    { code: 'CUZ', city: 'Cusco', country: 'Peru', lat: -13.5358, lng: -71.9389, name: 'Alejandro Velasco Astete International Airport' },
    { code: 'AQP', city: 'Arequipa', country: 'Peru', lat: -16.3411, lng: -71.5831, name: 'Alfredo Rodríguez Ballón International Airport' },
    { code: 'BOG', city: 'Bogotá', country: 'Colômbia', lat: 4.7016, lng: -74.1469, name: 'El Dorado International Airport' },
    { code: 'MDE', city: 'Medellín', country: 'Colômbia', lat: 6.1644, lng: -75.4231, name: 'José María Córdova International Airport' },
    { code: 'CLO', city: 'Cali', country: 'Colômbia', lat: 3.5430, lng: -76.3816, name: 'Alfonso Bonilla Aragón International Airport' },
    { code: 'CTG', city: 'Cartagena', country: 'Colômbia', lat: 10.4425, lng: -75.5130, name: 'Rafael Núñez International Airport' },
    { code: 'CCS', city: 'Caracas', country: 'Venezuela', lat: 10.6014, lng: -66.9911, name: 'Simón Bolívar International Airport' },
    { code: 'MAR', city: 'Maracaibo', country: 'Venezuela', lat: 10.5581, lng: -71.7289, name: 'La Chinita International Airport' },
    { code: 'GEO', city: 'Georgetown', country: 'Guiana', lat: 6.4986, lng: -58.2542, name: 'Cheddi Jagan International Airport' },
    { code: 'PBM', city: 'Paramaribo', country: 'Suriname', lat: 5.4528, lng: -55.1878, name: 'Johan Adolf Pengel International Airport' },
    { code: 'UIO', city: 'Quito', country: 'Equador', lat: -0.1292, lng: -78.3578, name: 'Mariscal Sucre International Airport' },
    { code: 'GYE', city: 'Guayaquil', country: 'Equador', lat: -2.1578, lng: -79.8831, name: 'José Joaquín de Olmedo International Airport' },
    { code: 'LPB', city: 'La Paz', country: 'Bolívia', lat: -16.5133, lng: -68.1922, name: 'El Alto International Airport' },
    { code: 'SRE', city: 'Santa Cruz', country: 'Bolívia', lat: -17.6447, lng: -63.1356, name: 'Viru Viru International Airport' },
    { code: 'ASU', city: 'Assunção', country: 'Paraguai', lat: -25.2394, lng: -57.5197, name: 'Silvio Pettirossi International Airport' },
    { code: 'MVD', city: 'Montevidéu', country: 'Uruguai', lat: -34.8381, lng: -56.0306, name: 'Carrasco International Airport' },

    // AMÉRICA CENTRAL E MÉXICO
    { code: 'MEX', city: 'Mexico City', country: 'México', lat: 19.4363, lng: -99.0721, name: 'Mexico City International Airport' },
    { code: 'CUN', city: 'Cancún', country: 'México', lat: 21.0364, lng: -86.8770, name: 'Cancún International Airport' },
    { code: 'PVR', city: 'Puerto Vallarta', country: 'México', lat: 20.6801, lng: -105.2544, name: 'Licenciado Gustavo Díaz Ordaz International Airport' },
    { code: 'GDL', city: 'Guadalajara', country: 'México', lat: 20.5218, lng: -103.3111, name: 'Miguel Hidalgo y Costilla Guadalajara International Airport' },
    { code: 'MTY', city: 'Monterrey', country: 'México', lat: 25.7785, lng: -100.1069, name: 'General Mariano Escobedo International Airport' },
    { code: 'CZM', city: 'Cozumel', country: 'México', lat: 20.5225, lng: -86.9256, name: 'Cozumel International Airport' },
    { code: 'SJD', city: 'Los Cabos', country: 'México', lat: 23.1518, lng: -109.7211, name: 'Los Cabos International Airport' },
    { code: 'TIJ', city: 'Tijuana', country: 'México', lat: 32.5411, lng: -116.9700, name: 'General Abelardo L. Rodríguez International Airport' },
    { code: 'MZT', city: 'Mazatlán', country: 'México', lat: 23.1614, lng: -106.2658, name: 'General Rafael Buelna International Airport' },
    { code: 'ACA', city: 'Acapulco', country: 'México', lat: 16.7569, lng: -99.7539, name: 'General Juan N. Álvarez International Airport' },
    { code: 'PTY', city: 'Panama City', country: 'Panamá', lat: 9.0714, lng: -79.3834, name: 'Tocumen International Airport' },
    { code: 'PAC', city: 'Panama City', country: 'Panamá', lat: 8.9733, lng: -79.5556, name: 'Marcos A. Gelabert International Airport' },
    { code: 'SJO', city: 'San José', country: 'Costa Rica', lat: 9.9939, lng: -84.2089, name: 'Juan Santamaría International Airport' },
    { code: 'LIR', city: 'Liberia', country: 'Costa Rica', lat: 10.5933, lng: -85.5444, name: 'Daniel Oduber Quirós International Airport' },
    { code: 'TGU', city: 'Tegucigalpa', country: 'Honduras', lat: 14.0608, lng: -87.2172, name: 'Toncontín International Airport' },
    { code: 'SAP', city: 'San Pedro Sula', country: 'Honduras', lat: 15.4528, lng: -87.9236, name: 'Ramón Villeda Morales International Airport' },
    { code: 'SAL', city: 'San Salvador', country: 'El Salvador', lat: 13.4409, lng: -89.0556, name: 'Monseñor Óscar Arnulfo Romero International Airport' },
    { code: 'GUA', city: 'Guatemala City', country: 'Guatemala', lat: 14.5833, lng: -90.5275, name: 'La Aurora International Airport' },
    { code: 'BZE', city: 'Belize City', country: 'Belize', lat: 17.5394, lng: -88.3083, name: 'Philip S. W. Goldson International Airport' },
    { code: 'MGA', city: 'Managua', country: 'Nicarágua', lat: 12.1414, lng: -86.1681, name: 'Augusto C. Sandino International Airport' },

    // EUROPA - Expandido
    { code: 'LHR', city: 'London', country: 'Reino Unido', lat: 51.4700, lng: -0.4543, name: 'Heathrow Airport' },
    { code: 'LGW', city: 'London', country: 'Reino Unido', lat: 51.1537, lng: -0.1821, name: 'Gatwick Airport' },
    { code: 'STN', city: 'London', country: 'Reino Unido', lat: 51.8860, lng: 0.2389, name: 'Stansted Airport' },
    { code: 'LTN', city: 'London', country: 'Reino Unido', lat: 51.8763, lng: -0.3717, name: 'Luton Airport' },
    { code: 'LCY', city: 'London', country: 'Reino Unido', lat: 51.5048, lng: 0.0495, name: 'London City Airport' },
    { code: 'BHX', city: 'Birmingham', country: 'Reino Unido', lat: 52.4539, lng: -1.7480, name: 'Birmingham Airport' },
    { code: 'MAN', city: 'Manchester', country: 'Reino Unido', lat: 53.3537, lng: -2.2750, name: 'Manchester Airport' },
    { code: 'EDI', city: 'Edinburgh', country: 'Reino Unido', lat: 55.9500, lng: -3.3725, name: 'Edinburgh Airport' },
    { code: 'GLA', city: 'Glasgow', country: 'Reino Unido', lat: 55.8719, lng: -4.4331, name: 'Glasgow International Airport' },
    { code: 'CDG', city: 'Paris', country: 'França', lat: 49.0097, lng: 2.5479, name: 'Charles de Gaulle Airport' },
    { code: 'ORY', city: 'Paris', country: 'França', lat: 48.7233, lng: 2.3794, name: 'Orly Airport' },
    { code: 'LBG', city: 'Paris', country: 'França', lat: 48.9694, lng: 2.4414, name: 'Le Bourget Airport' },
    { code: 'NCE', city: 'Nice', country: 'França', lat: 43.6653, lng: 7.2150, name: 'Nice Côte d\'Azur Airport' },
    { code: 'MRS', city: 'Marseille', country: 'França', lat: 43.4393, lng: 5.2214, name: 'Marseille Provence Airport' },
    { code: 'LYS', city: 'Lyon', country: 'França', lat: 45.7256, lng: 5.0811, name: 'Lyon-Saint Exupéry Airport' },
    { code: 'TLS', city: 'Toulouse', country: 'França', lat: 43.6289, lng: 1.3639, name: 'Toulouse-Blagnac Airport' },
    { code: 'BIQ', city: 'Biarritz', country: 'França', lat: 43.4683, lng: -1.5231, name: 'Biarritz Airport' },
    { code: 'FRA', city: 'Frankfurt', country: 'Alemanha', lat: 50.0379, lng: 8.5622, name: 'Frankfurt Airport' },
    { code: 'MUC', city: 'Munich', country: 'Alemanha', lat: 48.3538, lng: 11.7861, name: 'Munich Airport' },
    { code: 'DUS', city: 'Düsseldorf', country: 'Alemanha', lat: 51.2895, lng: 6.7668, name: 'Düsseldorf Airport' },
    { code: 'TXL', city: 'Berlin', country: 'Alemanha', lat: 52.5597, lng: 13.2877, name: 'Berlin Tegel Airport' },
    { code: 'HAM', city: 'Hamburg', country: 'Alemanha', lat: 53.6304, lng: 9.9882, name: 'Hamburg Airport' },
    { code: 'CGN', city: 'Cologne', country: 'Alemanha', lat: 50.8659, lng: 7.1427, name: 'Cologne Bonn Airport' },
    { code: 'AMS', city: 'Amsterdam', country: 'Holanda', lat: 52.3105, lng: 4.7683, name: 'Amsterdam Airport Schiphol' },
    { code: 'BRU', city: 'Brussels', country: 'Bélgica', lat: 50.9014, lng: 4.4844, name: 'Brussels Airport' },
    { code: 'ANR', city: 'Antwerp', country: 'Bélgica', lat: 51.1894, lng: 4.4603, name: 'Antwerp International Airport' },
    { code: 'MAD', city: 'Madrid', country: 'Espanha', lat: 40.4839, lng: -3.5680, name: 'Adolfo Suárez Madrid–Barajas Airport' },
    { code: 'BCN', city: 'Barcelona', country: 'Espanha', lat: 41.2974, lng: 2.0833, name: 'Josep Tarradellas Barcelona-El Prat Airport' },
    { code: 'PMI', city: 'Palma', country: 'Espanha', lat: 39.5517, lng: 2.7388, name: 'Palma de Mallorca Airport' },
    { code: 'SVQ', city: 'Seville', country: 'Espanha', lat: 37.4180, lng: -5.8931, name: 'Seville Airport' },
    { code: 'VLC', city: 'Valencia', country: 'Espanha', lat: 39.4893, lng: -0.4816, name: 'Valencia Airport' },
    { code: 'IBZ', city: 'Ibiza', country: 'Espanha', lat: 38.8729, lng: 1.3731, name: 'Ibiza Airport' },
    { code: 'LIS', city: 'Lisbon', country: 'Portugal', lat: 38.7813, lng: -9.1361, name: 'Lisbon Airport' },
    { code: 'OPO', city: 'Porto', country: 'Portugal', lat: 41.2481, lng: -8.6814, name: 'Francisco Sá Carneiro Airport' },
    { code: 'FNC', city: 'Funchal', country: 'Portugal', lat: 32.6978, lng: -16.7745, name: 'Cristiano Ronaldo International Airport' },
    { code: 'FCO', city: 'Rome', country: 'Itália', lat: 41.7999, lng: 12.2462, name: 'Leonardo da Vinci International Airport' },
    { code: 'CIA', city: 'Rome', country: 'Itália', lat: 41.7994, lng: 12.5949, name: 'Ciampino Airport' },
    { code: 'MXP', city: 'Milan', country: 'Itália', lat: 45.6306, lng: 8.7281, name: 'Malpensa Airport' },
    { code: 'LIN', city: 'Milan', country: 'Itália', lat: 45.4454, lng: 9.2761, name: 'Linate Airport' },
    { code: 'VCE', city: 'Venice', country: 'Itália', lat: 45.5053, lng: 12.3519, name: 'Marco Polo Airport' },
    { code: 'NAP', city: 'Naples', country: 'Itália', lat: 40.8860, lng: 14.2906, name: 'Naples International Airport' },
    { code: 'ZUR', city: 'Zurich', country: 'Suíça', lat: 47.4582, lng: 8.5480, name: 'Zurich Airport' },
    { code: 'GVA', city: 'Geneva', country: 'Suíça', lat: 46.2381, lng: 6.1089, name: 'Geneva Airport' },
    { code: 'BSL', city: 'Basel', country: 'Suíça', lat: 47.5896, lng: 7.5291, name: 'EuroAirport Basel-Mulhouse-Freiburg' },
    { code: 'VIE', city: 'Vienna', country: 'Áustria', lat: 48.1103, lng: 16.5697, name: 'Vienna International Airport' },
    { code: 'SZG', city: 'Salzburg', country: 'Áustria', lat: 47.7933, lng: 13.0043, name: 'Salzburg Airport' },
    { code: 'INN', city: 'Innsbruck', country: 'Áustria', lat: 47.2602, lng: 11.3439, name: 'Innsbruck Airport' },
    { code: 'CPH', city: 'Copenhagen', country: 'Dinamarca', lat: 55.6181, lng: 12.6560, name: 'Copenhagen Airport' },
    { code: 'OSL', city: 'Oslo', country: 'Noruega', lat: 60.1939, lng: 11.1004, name: 'Oslo Airport' },
    { code: 'ARN', city: 'Stockholm', country: 'Suécia', lat: 59.6519, lng: 17.9186, name: 'Stockholm Arlanda Airport' },
    { code: 'HEL', city: 'Helsinki', country: 'Finlândia', lat: 60.3172, lng: 24.9633, name: 'Helsinki-Vantaa Airport' },

    // ÁSIA
    { code: 'NRT', city: 'Tokyo', country: 'Japão', lat: 35.7720, lng: 140.3929, name: 'Narita International Airport' },
    { code: 'HND', city: 'Tokyo', country: 'Japão', lat: 35.5494, lng: 139.7798, name: 'Haneda Airport' },
    { code: 'KIX', city: 'Osaka', country: 'Japão', lat: 34.4347, lng: 135.2441, name: 'Kansai International Airport' },
    { code: 'ICN', city: 'Seoul', country: 'Coreia do Sul', lat: 37.4602, lng: 126.4407, name: 'Incheon International Airport' },
    { code: 'GMP', city: 'Seoul', country: 'Coreia do Sul', lat: 37.5583, lng: 126.7906, name: 'Gimpo International Airport' },
    { code: 'PVG', city: 'Shanghai', country: 'China', lat: 31.1443, lng: 121.8083, name: 'Shanghai Pudong International Airport' },
    { code: 'SHA', city: 'Shanghai', country: 'China', lat: 31.1979, lng: 121.3364, name: 'Shanghai Hongqiao International Airport' },
    { code: 'PEK', city: 'Beijing', country: 'China', lat: 39.5098, lng: 116.4105, name: 'Beijing Capital International Airport' },
    { code: 'CAN', city: 'Guangzhou', country: 'China', lat: 23.3924, lng: 113.2988, name: 'Guangzhou Baiyun International Airport' },
    { code: 'SZX', city: 'Shenzhen', country: 'China', lat: 22.6393, lng: 113.8111, name: 'Shenzhen Bao\'an International Airport' },
    { code: 'HKG', city: 'Hong Kong', country: 'Hong Kong', lat: 22.3080, lng: 113.9185, name: 'Hong Kong International Airport' },
    { code: 'TPE', city: 'Taipei', country: 'Taiwan', lat: 25.0797, lng: 121.2342, name: 'Taiwan Taoyuan International Airport' },
    { code: 'SIN', city: 'Singapore', country: 'Singapura', lat: 1.3644, lng: 103.9915, name: 'Singapore Changi Airport' },
    { code: 'BKK', city: 'Bangkok', country: 'Tailândia', lat: 13.6900, lng: 100.7501, name: 'Suvarnabhumi Airport' },
    { code: 'DMK', city: 'Bangkok', country: 'Tailândia', lat: 13.9126, lng: 100.6060, name: 'Don Mueang International Airport' },
    { code: 'KUL', city: 'Kuala Lumpur', country: 'Malásia', lat: 2.7456, lng: 101.7072, name: 'Kuala Lumpur International Airport' },
    { code: 'CGK', city: 'Jakarta', country: 'Indonésia', lat: -6.1256, lng: 106.6558, name: 'Soekarno-Hatta International Airport' },
    { code: 'DPS', city: 'Denpasar', country: 'Indonésia', lat: -8.7467, lng: 115.1672, name: 'Ngurah Rai International Airport' },
    { code: 'MNL', city: 'Manila', country: 'Filipinas', lat: 14.5086, lng: 121.0194, name: 'Ninoy Aquino International Airport' },
    { code: 'DEL', city: 'New Delhi', country: 'Índia', lat: 28.5665, lng: 77.1031, name: 'Indira Gandhi International Airport' },
    { code: 'BOM', city: 'Mumbai', country: 'Índia', lat: 19.0896, lng: 72.8656, name: 'Chhatrapati Shivaji Maharaj International Airport' },

    // ORIENTE MÉDIO - Expandido
    { code: 'DXB', city: 'Dubai', country: 'Emirados Árabes Unidos', lat: 25.2532, lng: 55.3657, name: 'Dubai International Airport' },
    { code: 'DWC', city: 'Dubai', country: 'Emirados Árabes Unidos', lat: 24.8967, lng: 55.1611, name: 'Al Maktoum International Airport' },
    { code: 'AUH', city: 'Abu Dhabi', country: 'Emirados Árabes Unidos', lat: 24.4330, lng: 54.6511, name: 'Abu Dhabi International Airport' },
    { code: 'DOH', city: 'Doha', country: 'Qatar', lat: 25.2731, lng: 51.6080, name: 'Hamad International Airport' },
    { code: 'KWI', city: 'Kuwait City', country: 'Kuwait', lat: 29.2267, lng: 47.9689, name: 'Kuwait International Airport' },
    { code: 'BAH', city: 'Manama', country: 'Bahrain', lat: 26.2708, lng: 50.6336, name: 'Bahrain International Airport' },
    { code: 'MCT', city: 'Muscat', country: 'Omã', lat: 23.5933, lng: 58.2844, name: 'Muscat International Airport' },
    { code: 'RUH', city: 'Riyadh', country: 'Arábia Saudita', lat: 24.9576, lng: 46.6988, name: 'King Khalid International Airport' },
    { code: 'JED', city: 'Jeddah', country: 'Arábia Saudita', lat: 21.6796, lng: 39.1565, name: 'King Abdulaziz International Airport' },

    // ÁFRICA - Expandido
    { code: 'JNB', city: 'Johannesburg', country: 'África do Sul', lat: -26.1367, lng: 28.2411, name: 'OR Tambo International Airport' },
    { code: 'CPT', city: 'Cape Town', country: 'África do Sul', lat: -33.9715, lng: 18.6021, name: 'Cape Town International Airport' },
    { code: 'DUR', city: 'Durban', country: 'África do Sul', lat: -29.9144, lng: 30.9506, name: 'King Shaka International Airport' },
    { code: 'CAI', city: 'Cairo', country: 'Egito', lat: 30.1219, lng: 31.4056, name: 'Cairo International Airport' },
    { code: 'HRG', city: 'Hurghada', country: 'Egito', lat: 27.1783, lng: 33.7994, name: 'Hurghada International Airport' },
    { code: 'SSH', city: 'Sharm El Sheikh', country: 'Egito', lat: 27.9773, lng: 34.3950, name: 'Sharm El Sheikh International Airport' },
    { code: 'CMN', city: 'Casablanca', country: 'Marrocos', lat: 33.3675, lng: -7.5897, name: 'Mohammed V International Airport' },
    { code: 'RAK', city: 'Marrakech', country: 'Marrocos', lat: 31.6069, lng: -8.0363, name: 'Marrakech Menara Airport' },
    { code: 'TUN', city: 'Tunis', country: 'Tunísia', lat: 36.8510, lng: 10.2272, name: 'Tunis-Carthage International Airport' },
    { code: 'ALG', city: 'Algiers', country: 'Argélia', lat: 36.6910, lng: 3.2154, name: 'Houari Boumediene Airport' },
    { code: 'LOS', city: 'Lagos', country: 'Nigéria', lat: 6.5774, lng: 3.3211, name: 'Murtala Muhammed International Airport' },
    { code: 'ABV', city: 'Abuja', country: 'Nigéria', lat: 9.0068, lng: 7.2632, name: 'Nnamdi Azikiwe International Airport' },
    { code: 'ACC', city: 'Accra', country: 'Gana', lat: 5.6052, lng: -0.1719, name: 'Kotoka International Airport' },
    { code: 'DKR', city: 'Dakar', country: 'Senegal', lat: 14.7397, lng: -17.4902, name: 'Blaise Diagne International Airport' },

    // OCEANIA - Expandido
    { code: 'SYD', city: 'Sydney', country: 'Austrália', lat: -33.9399, lng: 151.1753, name: 'Kingsford Smith Airport' },
    { code: 'MEL', city: 'Melbourne', country: 'Austrália', lat: -37.6690, lng: 144.8410, name: 'Melbourne Airport' },
    { code: 'BNE', city: 'Brisbane', country: 'Austrália', lat: -27.3942, lng: 153.1218, name: 'Brisbane Airport' },
    { code: 'PER', city: 'Perth', country: 'Austrália', lat: -31.9403, lng: 115.9669, name: 'Perth Airport' },
    { code: 'ADL', city: 'Adelaide', country: 'Austrália', lat: -34.9470, lng: 138.5306, name: 'Adelaide Airport' },
    { code: 'DRW', city: 'Darwin', country: 'Austrália', lat: -12.4167, lng: 130.8833, name: 'Darwin International Airport' },
    { code: 'CNS', city: 'Cairns', country: 'Austrália', lat: -16.8858, lng: 145.7781, name: 'Cairns Airport' },
    { code: 'AKL', city: 'Auckland', country: 'Nova Zelândia', lat: -37.0082, lng: 174.7850, name: 'Auckland Airport' },
    { code: 'CHC', city: 'Christchurch', country: 'Nova Zelândia', lat: -43.4894, lng: 172.5320, name: 'Christchurch Airport' },
    { code: 'WLG', city: 'Wellington', country: 'Nova Zelândia', lat: -41.3276, lng: 174.8052, name: 'Wellington Airport' },
    { code: 'ZQN', city: 'Queenstown', country: 'Nova Zelândia', lat: -45.0211, lng: 168.7392, name: 'Queenstown Airport' },
    
    // ATLÂNTICO NORTE
    { code: 'KEF', city: 'Reykjavik', country: 'Islândia', lat: 64.1300, lng: -21.9406, name: 'Keflavík International Airport' },
    { code: 'SFJ', city: 'Kangerlussuaq', country: 'Groelândia', lat: 67.0122, lng: -50.7116, name: 'Kangerlussuaq Airport' },
    { code: 'BGO', city: 'Bergen', country: 'Noruega', lat: 60.2934, lng: 5.2181, name: 'Bergen Airport' },
    { code: 'TRD', city: 'Trondheim', country: 'Noruega', lat: 63.4578, lng: 10.9239, name: 'Trondheim Airport' },
    { code: 'FAE', city: 'Tórshavn', country: 'Ilhas Faroe', lat: 62.0636, lng: -7.2772, name: 'Vágar Airport' },

    // AÇORES E MADEIRA
    { code: 'PDL', city: 'Ponta Delgada', country: 'Portugal (Açores)', lat: 37.7412, lng: -25.6979, name: 'João Paulo II Airport' },
    { code: 'TER', city: 'Terceira', country: 'Portugal (Açores)', lat: 38.7617, lng: -27.0909, name: 'Terceira Airport' },
    { code: 'HOR', city: 'Horta', country: 'Portugal (Açores)', lat: 38.5197, lng: -28.7156, name: 'Horta Airport' },

    // PACÍFICO - Ilhas estratégicas para travessias oceânicas
    { code: 'HNL', city: 'Honolulu', country: 'Estados Unidos (Havaí)', lat: 21.3099, lng: -157.8581, name: 'Daniel K. Inouye International Airport' },
    { code: 'KOA', city: 'Kailua-Kona', country: 'Estados Unidos (Havaí)', lat: 19.7388, lng: -156.0456, name: 'Ellison Onizuka Kona International Airport' },
    { code: 'OGG', city: 'Kahului', country: 'Estados Unidos (Havaí)', lat: 20.8986, lng: -156.4306, name: 'Kahului Airport' },
    { code: 'GUM', city: 'Tamuning', country: 'Guam', lat: 13.4834, lng: 144.7960, name: 'Antonio B. Won Pat International Airport' },
    { code: 'SPN', city: 'Saipan', country: 'Ilhas Marianas do Norte', lat: 15.1190, lng: 145.7297, name: 'Saipan International Airport' },
    { code: 'PPG', city: 'Pago Pago', country: 'Samoa Americana', lat: -14.3311, lng: -170.7106, name: 'Pago Pago International Airport' },
    { code: 'APW', city: 'Apia', country: 'Samoa', lat: -13.8300, lng: -172.0081, name: 'Faleolo International Airport' },
    { code: 'NAN', city: 'Nadi', country: 'Fiji', lat: -17.7553, lng: 177.4533, name: 'Nadi International Airport' },
    { code: 'SUV', city: 'Suva', country: 'Fiji', lat: -18.0439, lng: 178.5594, name: 'Nausori Airport' },
    { code: 'NOU', city: 'Nouméa', country: 'Nova Caledônia', lat: -22.0146, lng: 166.2130, name: 'Nouméa Magenta Airport' },
    { code: 'POM', city: 'Port Moresby', country: 'Papua Nova Guiné', lat: -9.4439, lng: 147.2200, name: 'Jacksons International Airport' },

    // ILHAS DO ATLÂNTICO SUL E ÍNDICO - Estratégicas para volta ao mundo
    { code: 'ASI', city: 'Jamestown', country: 'Santa Helena', lat: -15.9625, lng: -14.3967, name: 'Saint Helena Airport' },
    { code: 'RAI', city: 'Mindelo', country: 'Cabo Verde', lat: 16.8333, lng: -25.0553, name: 'Cesária Évora Airport' },
    { code: 'SID', city: 'Praia', country: 'Cabo Verde', lat: 14.9453, lng: -23.4939, name: 'Nelson Mandela International Airport' },
    { code: 'MRU', city: 'Port Louis', country: 'Maurício', lat: -20.4302, lng: 57.6836, name: 'Sir Seewoosagur Ramgoolam International Airport' },
    { code: 'RUN', city: 'Saint-Denis', country: 'Reunião', lat: -20.8872, lng: 55.5103, name: 'Roland Garros Airport' },
    { code: 'SEZ', city: 'Victoria', country: 'Seychelles', lat: -4.6743, lng: 55.5218, name: 'Seychelles International Airport' },
    { code: 'MLE', city: 'Malé', country: 'Maldivas', lat: 4.1917, lng: 73.5289, name: 'Velana International Airport' },

    // SIBÉRIA E EXTREMO ORIENTE RUSSO - Para rotas polares e transcontinentais
    { code: 'SVO', city: 'Moscow', country: 'Rússia', lat: 55.9728, lng: 37.4147, name: 'Sheremetyevo International Airport' },
    { code: 'VVO', city: 'Vladivostok', country: 'Rússia', lat: 43.3989, lng: 132.1478, name: 'Vladivostok International Airport' },
    { code: 'KHV', city: 'Khabarovsk', country: 'Rússia', lat: 48.5278, lng: 135.1883, name: 'Khabarovsk Novy Airport' },
    { code: 'YKS', city: 'Yakutsk', country: 'Rússia', lat: 62.0928, lng: 129.7708, name: 'Yakutsk Airport' },

    // ÍNDIA - Expandido drasticamente
    { code: 'BLR', city: 'Bangalore', country: 'Índia', lat: 13.1986, lng: 77.7066, name: 'Kempegowda International Airport' },
    { code: 'MAA', city: 'Chennai', country: 'Índia', lat: 12.9941, lng: 80.1709, name: 'Chennai International Airport' },
    { code: 'HYD', city: 'Hyderabad', country: 'Índia', lat: 17.2403, lng: 78.4294, name: 'Rajiv Gandhi International Airport' },
    { code: 'CCU', city: 'Kolkata', country: 'Índia', lat: 22.6547, lng: 88.4467, name: 'Netaji Subhash Chandra Bose International Airport' },
    { code: 'COK', city: 'Kochi', country: 'Índia', lat: 9.9595, lng: 76.2673, name: 'Cochin International Airport' },
    { code: 'GOI', city: 'Goa', country: 'Índia', lat: 15.3809, lng: 73.8314, name: 'Manohar International Airport' },
    { code: 'PNQ', city: 'Pune', country: 'Índia', lat: 18.5822, lng: 73.9197, name: 'Pune Airport' },
    { code: 'AMD', city: 'Ahmedabad', country: 'Índia', lat: 23.0732, lng: 72.6347, name: 'Sardar Vallabhbhai Patel International Airport' },
    { code: 'JAI', city: 'Jaipur', country: 'Índia', lat: 26.8242, lng: 75.8122, name: 'Jaipur International Airport' },
    { code: 'LKO', city: 'Lucknow', country: 'Índia', lat: 26.7606, lng: 80.8893, name: 'Chaudhary Charan Singh International Airport' },
    { code: 'NAG', city: 'Nagpur', country: 'Índia', lat: 21.0924, lng: 79.0473, name: 'Dr. Babasaheb Ambedkar International Airport' },
    { code: 'BBI', city: 'Bhubaneswar', country: 'Índia', lat: 20.2444, lng: 85.8178, name: 'Biju Patnaik International Airport' },
    { code: 'IXC', city: 'Chandigarh', country: 'Índia', lat: 30.6735, lng: 76.7882, name: 'Chandigarh Airport' },
    { code: 'GAU', city: 'Guwahati', country: 'Índia', lat: 26.1061, lng: 91.5856, name: 'Lokpriya Gopinath Bordoloi International Airport' },

    // BANGLADESH
    { code: 'DAC', city: 'Dhaka', country: 'Bangladesh', lat: 23.8433, lng: 90.3978, name: 'Hazrat Shahjalal International Airport' },
    { code: 'CGP', city: 'Chittagong', country: 'Bangladesh', lat: 22.2496, lng: 91.8133, name: 'Shah Amanat International Airport' },
    { code: 'ZYL', city: 'Sylhet', country: 'Bangladesh', lat: 24.9633, lng: 91.8733, name: 'Osmani International Airport' },

    // TAILÂNDIA - Expandido
    { code: 'HKT', city: 'Phuket', country: 'Tailândia', lat: 8.1132, lng: 98.3169, name: 'Phuket International Airport' },
    { code: 'CNX', city: 'Chiang Mai', country: 'Tailândia', lat: 18.7667, lng: 98.9628, name: 'Chiang Mai International Airport' },
    { code: 'USM', city: 'Koh Samui', country: 'Tailândia', lat: 9.5478, lng: 100.0622, name: 'Samui Airport' },
    { code: 'KBV', city: 'Krabi', country: 'Tailândia', lat: 8.0992, lng: 98.9886, name: 'Krabi Airport' },
    { code: 'CEI', city: 'Chiang Rai', country: 'Tailândia', lat: 19.9523, lng: 99.8829, name: 'Mae Fah Luang - Chiang Rai International Airport' },
    { code: 'HDY', city: 'Hat Yai', country: 'Tailândia', lat: 6.9331, lng: 100.3931, name: 'Hat Yai International Airport' },
    { code: 'URT', city: 'Udon Thani', country: 'Tailândia', lat: 17.3864, lng: 102.7883, name: 'Udon Thani International Airport' },
    { code: 'UTP', city: 'U-Tapao', country: 'Tailândia', lat: 12.6797, lng: 101.0053, name: 'U-Tapao International Airport' },

    // SINGAPURA - Expandido
    { code: 'XSP', city: 'Singapore', country: 'Singapura', lat: 1.4167, lng: 103.8667, name: 'Seletar Airport' },

    // FILIPINAS - Expandido drasticamente
    { code: 'CEB', city: 'Cebu', country: 'Filipinas', lat: 10.3075, lng: 123.9794, name: 'Mactan-Cebu International Airport' },
    { code: 'DVO', city: 'Davao', country: 'Filipinas', lat: 7.1253, lng: 125.6456, name: 'Francisco Bangoy International Airport' },
    { code: 'CRK', city: 'Clark', country: 'Filipinas', lat: 15.1856, lng: 120.5603, name: 'Clark International Airport' },
    { code: 'ILO', city: 'Iloilo', country: 'Filipinas', lat: 10.8331, lng: 122.4936, name: 'Iloilo International Airport' },
    { code: 'BCD', city: 'Bacolod', country: 'Filipinas', lat: 10.6456, lng: 123.0158, name: 'Bacolod-Silay Airport' },
    { code: 'CGY', city: 'Cagayan de Oro', country: 'Filipinas', lat: 8.4156, lng: 124.6111, name: 'Laguindingan Airport' },
    { code: 'PPS', city: 'Puerto Princesa', country: 'Filipinas', lat: 9.7422, lng: 118.7589, name: 'Puerto Princesa Airport' },
    { code: 'TAC', city: 'Tacloban', country: 'Filipinas', lat: 11.2278, lng: 125.0278, name: 'Daniel Z. Romualdez Airport' },
    { code: 'BXU', city: 'Butuan', country: 'Filipinas', lat: 8.9517, lng: 125.4789, name: 'Bancasi Airport' },
    { code: 'KLO', city: 'Kalibo', country: 'Filipinas', lat: 11.6794, lng: 122.3761, name: 'Kalibo International Airport' },
    { code: 'MPH', city: 'Caticlan', country: 'Filipinas', lat: 12.2203, lng: 121.9539, name: 'Godofredo P. Ramos Airport' },
    { code: 'ZAM', city: 'Zamboanga', country: 'Filipinas', lat: 6.9222, lng: 122.0597, name: 'Zamboanga International Airport' },

    // TAIWAN - Expandido
    { code: 'KHH', city: 'Kaohsiung', country: 'Taiwan', lat: 22.5771, lng: 120.3500, name: 'Kaohsiung International Airport' },
    { code: 'RMQ', city: 'Taichung', country: 'Taiwan', lat: 24.2647, lng: 120.6211, name: 'Taichung International Airport' },
    { code: 'TNN', city: 'Tainan', country: 'Taiwan', lat: 22.9503, lng: 120.2058, name: 'Tainan Airport' },
    { code: 'HUN', city: 'Hualien', country: 'Taiwan', lat: 23.9939, lng: 121.6175, name: 'Hualien Airport' },
    { code: 'TTT', city: 'Taitung', country: 'Taiwan', lat: 22.7550, lng: 121.1019, name: 'Taitung Airport' },
    { code: 'MZG', city: 'Magong', country: 'Taiwan', lat: 23.5686, lng: 119.6281, name: 'Magong Airport' },
    { code: 'KNH', city: 'Kinmen', country: 'Taiwan', lat: 24.4278, lng: 118.3597, name: 'Kinmen Airport' },

    // COREIA DO SUL - Expandido
    { code: 'PUS', city: 'Busan', country: 'Coreia do Sul', lat: 35.1795, lng: 128.9383, name: 'Gimhae International Airport' },
    { code: 'CJU', city: 'Jeju', country: 'Coreia do Sul', lat: 33.5111, lng: 126.4928, name: 'Jeju International Airport' },
    { code: 'TAE', city: 'Daegu', country: 'Coreia do Sul', lat: 35.8939, lng: 128.6586, name: 'Daegu International Airport' },
    { code: 'KWJ', city: 'Gwangju', country: 'Coreia do Sul', lat: 35.1264, lng: 126.8094, name: 'Gwangju Airport' },
    { code: 'CHN', city: 'Jeonju', country: 'Coreia do Sul', lat: 35.8781, lng: 127.1194, name: 'Cheongju International Airport' },
    { code: 'RSU', city: 'Yeosu', country: 'Coreia do Sul', lat: 34.8422, lng: 127.6172, name: 'Yeosu Airport' },
    { code: 'KPX', city: 'Pohang', country: 'Coreia do Sul', lat: 35.9878, lng: 129.4200, name: 'Pohang Airport' },

    // MALÁSIA - Expandido
    { code: 'PEN', city: 'Penang', country: 'Malásia', lat: 5.2970, lng: 100.2770, name: 'Penang International Airport' },
    { code: 'JHB', city: 'Johor Bahru', country: 'Malásia', lat: 1.6411, lng: 103.6697, name: 'Senai International Airport' },
    { code: 'KCH', city: 'Kuching', country: 'Malásia', lat: 1.4847, lng: 110.3467, name: 'Kuching International Airport' },
    { code: 'BKI', city: 'Kota Kinabalu', country: 'Malásia', lat: 5.9372, lng: 116.0511, name: 'Kota Kinabalu International Airport' },
    { code: 'MYY', city: 'Miri', country: 'Malásia', lat: 4.3228, lng: 113.9869, name: 'Miri Airport' },
    { code: 'LGK', city: 'Langkawi', country: 'Malásia', lat: 6.3297, lng: 99.7289, name: 'Langkawi International Airport' },

    // INDONÉSIA - Expandido
    { code: 'MLG', city: 'Malang', country: 'Indonésia', lat: -7.9267, lng: 112.7144, name: 'Abdul Rachman Saleh Airport' },
    { code: 'JOG', city: 'Yogyakarta', country: 'Indonésia', lat: -7.7879, lng: 110.4317, name: 'Yogyakarta International Airport' },
    { code: 'SOC', city: 'Solo', country: 'Indonésia', lat: -7.5161, lng: 110.7569, name: 'Adisumarmo International Airport' },
    { code: 'SRG', city: 'Semarang', country: 'Indonésia', lat: -6.9714, lng: 110.3744, name: 'Ahmad Yani International Airport' },
    { code: 'MDC', city: 'Manado', country: 'Indonésia', lat: 1.5492, lng: 124.9267, name: 'Sam Ratulangi International Airport' },
    { code: 'UPG', city: 'Makassar', country: 'Indonésia', lat: -5.0617, lng: 119.5542, name: 'Sultan Hasanuddin International Airport' },
    { code: 'BDO', city: 'Bandung', country: 'Indonésia', lat: -6.9006, lng: 107.5764, name: 'Husein Sastranegara International Airport' },
    { code: 'PKU', city: 'Pekanbaru', country: 'Indonésia', lat: 0.4608, lng: 101.4450, name: 'Sultan Syarif Kasim II International Airport' },
    { code: 'PLM', city: 'Palembang', country: 'Indonésia', lat: -2.8983, lng: 104.7000, name: 'Sultan Mahmud Badaruddin II International Airport' }
];